# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
