# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-14 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='_value',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='charge',
            old_name='_date',
            new_name='transacted_at',
        ),
    ]
