# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-15 11:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20161215_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='onwers',
            field=models.ManyToManyField(related_name='shared_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
