# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-15 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_account_onwers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
